# Generated by Django 3.2 on 2024-06-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
