# Generated by Django 3.2 on 2024-06-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_customer_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_related', to='campaigns.campaign')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_customer', to='campaigns.customer')),
            ],
            options={
                'db_table': 'campaign_customers',
            },
        ),
        migrations.DeleteModel(
            name='TemplateCustomers',
        ),
    ]
